In [5]:
import pandas as pd
import numpy as np
import os
import h3 
import re

In [6]:
# building_df = pd.read_csv('OpenStreetMap/B_features.csv')
poi_df_B = pd.read_csv('OpenStreetMap/B_features.csv')

poi_df_B = poi_df_B[['osmid','building', 'geometry','amenity']]

# 初始化列表
lat = []
lon = []
h3_l7 = []

# 遍歷每一行
for i in range(poi_df_B.shape[0]):
    # 提取經緯度
    coordinates = re.findall("\d+\.?\d*", poi_df_B.geometry[i])
    if len(coordinates) < 1:
        continue  # 如果座標數據不完整，跳過該行
    else:
        # 提取緯度和經度
        latitude = float(coordinates[1])  # 緯度
        longitude = -float(coordinates[0])  # 經度
        lat.append(latitude)
        lon.append(longitude)
        
        # 轉換為 H3 L7 id
        h3_l7.append(h3.geo_to_h3(latitude, longitude, resolution=7))


# 新增列到有效的 DataFrame
poi_df_B['lat'] = lat
poi_df_B['lon'] = lon
poi_df_B['h3_l7'] = h3_l7

# 刪除 'geometry' 列
poi_df_B = poi_df_B.drop('geometry', axis=1)
poi_df_B = poi_df_B[poi_df_B.amenity.isna()]
poi_df_B = poi_df_B[poi_df_B.building != 'yes']
poi_df_B = poi_df_B.drop(['amenity'], axis=1) 
poi_df_B

<>:14: SyntaxWarning: invalid escape sequence '\d'
<>:14: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Yuan\AppData\Local\Temp\ipykernel_26984\3788611144.py:14: SyntaxWarning: invalid escape sequence '\d'
  coordinates = re.findall("\d+\.?\d*", poi_df_B.geometry[i])
C:\Users\Yuan\AppData\Local\Temp\ipykernel_26984\3788611144.py:2: DtypeWarning: Columns (2,5,7,8,10,12,14,15,17,18,19,20,22,23,24,25,26,27,28,29,30,32,33,34,35,36,38,39,40,42,43,44,46,48,49,50,53,54,55,56,57,59,61,62,63,64,65,66,67,68,69,70,71,72,73,74,76,77,78,79,80,81,82,83,84,85,87,88,90,91,93,94,95,96,97,98,99,100,102,104,105,106,107,108,110,112,113,114,115,116,117,118,119,120,121,127,128,129,130,131,137,138,139,140,141,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,168,169,170,171,172,173,174,175,176,177,178,179,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,223,225,226,227,228,229,230,231,232,233,235,236,237,238,239,240,241) have mixed types. Specify dtype option on import or set low_memory=False.
  poi_df_B = pd.read_csv('OpenStreetMap/B_features.csv')

             osmid     building        lat        lon            h3_l7
1       6635106080        house  36.747754 -76.069648  872af0c92ffffff
2       6635123737        house  36.748888 -76.070386  872af0c92ffffff
3       6994304373       bunker  36.793610 -76.042931  872af6349ffffff
4       6994304374       bunker  36.794322 -76.041312  872af6349ffffff
5       6994304375       bunker  36.792657 -76.043861  872af6349ffffff
...            ...          ...        ...        ...              ...
141948     9637418        house  36.858806 -76.170325  872af622cffffff
141953    11674759       school  36.819752 -76.076312  872af634effffff
141960    12032839  residential  36.790276 -76.111886  872af6266ffffff
141963    12199937   commercial  36.824307 -76.079470  872af634effffff
141964    12476502        hotel  36.861693 -75.978428  872af636cffffff

[134603 rows x 5 columns]

In [12]:
print(len(poi_df_B['building'].unique()))

39

In [8]:
# building_df = pd.read_csv('OpenStreetMap/B_features.csv')
poi_df_A = pd.read_csv('OpenStreetMap/A_features.csv')
# poi_df = poi_df[['osmid', 'amenity', 'ele', 'denomination', 'brand', 'cuisine',
#                     'healthcare', 'parking', 'geometry', 'height']
poi_df_A = poi_df_A[['osmid', 'amenity', 'geometry']]

# 初始化列表
lat = []
lon = []
h3_l7 = []

# 只挑選有效的行
valid_indices = []  # 用來記錄有效行的索引
# 遍歷每一行
for i in range(poi_df_A.shape[0]):
    # 提取經緯度
    coordinates = re.findall("\d+\.?\d*", poi_df_A.geometry[i])
    if len(coordinates) < 1:
        continue  # 如果座標數據不完整，跳過該行
    else:
        # 提取緯度和經度
        latitude = float(coordinates[1])  # 緯度
        longitude = -float(coordinates[0])  # 經度
        lat.append(latitude)
        lon.append(longitude)
        
        # 轉換為 H3 L7 id
        h3_l7.append(h3.geo_to_h3(latitude, longitude, resolution=7))
        
        # 記錄有效行的索引
        valid_indices.append(i)



# 新增列到有效的 DataFrame
poi_df_A['lat'] = lat
poi_df_A['lon'] = lon
poi_df_A['h3_l7'] = h3_l7

# 刪除 'geometry' 列
poi_df_A = poi_df_A.drop('geometry', axis=1)
poi_df_A['building'] = poi_df_A['amenity'] 
poi_df_A = poi_df_A.drop(['amenity'], axis=1) 
poi_df_A

<>:17: SyntaxWarning: invalid escape sequence '\d'
<>:17: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Yuan\AppData\Local\Temp\ipykernel_26984\2904713986.py:17: SyntaxWarning: invalid escape sequence '\d'
  coordinates = re.findall("\d+\.?\d*", poi_df_A.geometry[i])

          osmid        lat        lon            h3_l7          building
0     356567877  36.709595 -76.047987  872af626dffffff  place_of_worship
1     356567908  36.590430 -76.018540  872af052affffff        grave_yard
2     356567948  36.586005 -76.082863  872af051cffffff  place_of_worship
3     356568033  36.733205 -76.097433  872af626effffff  place_of_worship
4     356568069  36.557653 -76.073542  872af0519ffffff  place_of_worship
...         ...        ...        ...              ...               ...
3478   13825469  36.853923 -76.153865  872af6353ffffff  place_of_worship
3479   14020613  36.757505 -76.050832  872af0c92ffffff  place_of_worship
3480   14325039  36.872663 -76.139490  872af6350ffffff            clinic
3481   14756225  36.857801 -76.026476  872af636effffff           parking
3482   14756331  36.866456 -76.029736  872af6363ffffff           parking

[3483 rows x 5 columns]

In [10]:
print(len(poi_df_A['building'].unique()))

82

In [13]:
unique_valuesB = poi_df_B['building'].unique()
unique_valuesA = poi_df_A['building'].unique()
# 找出 A 和 B 中的重複值
duplicate_values = set(unique_valuesA) & set(unique_valuesB)  # 使用集合交集操作

# 將結果轉成列表或其他格式
duplicate_values_list = list(duplicate_values)
duplicate_values_list

['school', 'shelter', 'university', 'college', 'toilets', 'hospital']

In [12]:
unique_values = poi_df_B['building'].unique()
formatted_output = ', '.join(unique_values)  # 用逗號串接

print(formatted_output)

house, bunker, office, commercial, shelter, residential, public, roof, university, dormitory, chapel, greenhouse, apartments, garage, shed, retail, static_caravan, church, terrace, service, school, hospital, industrial, pavilion, commercial;yes, stadium, hotel, cabin, toilets, college, warehouse, sports_centre, detached, boathouse, barn, riding_hall, construction, ship, ruins

In [6]:
poi_df = pd.concat((poi_df_A, poi_df_B))

min_lat = min(poi_df['lat'])
max_lat = max(poi_df['lat'])
min_lon = min(poi_df['lon'])
max_lon = max(poi_df['lon'])
poi_df

            osmid        lat        lon            h3_l7          building
0       356567877  36.709595 -76.047987  872af626dffffff  place_of_worship
1       356567908  36.590430 -76.018540  872af052affffff        grave_yard
2       356567948  36.586005 -76.082863  872af051cffffff  place_of_worship
3       356568033  36.733205 -76.097433  872af626effffff  place_of_worship
4       356568069  36.557653 -76.073542  872af0519ffffff  place_of_worship
...           ...        ...        ...              ...               ...
141948    9637418  36.858806 -76.170325  872af622cffffff             house
141953   11674759  36.819752 -76.076312  872af634effffff            school
141960   12032839  36.790276 -76.111886  872af6266ffffff       residential
141963   12199937  36.824307 -76.079470  872af634effffff        commercial
141964   12476502  36.861693 -75.978428  872af636cffffff             hotel

[138086 rows x 5 columns]

In [7]:
ohca_df = pd.read_csv('OHCAs.csv')
h3_l7 = []

for i in range(ohca_df.shape[0]):
    h3_l7.append(h3.geo_to_h3(ohca_df.Latitude[i], ohca_df.Longitude[i], resolution=7))

ohca_df['h3_l7'] = h3_l7

if min_lat < min(ohca_df['Latitude']): min_lat = min(ohca_df['Latitude'])
if max_lat > max(ohca_df['Latitude']): max_lat = max(ohca_df['Latitude'])
if min_lon < min(ohca_df['Longitude']): min_lon = min(ohca_df['Longitude'])
if max_lon > max(ohca_df['Longitude']): max_lon = max(ohca_df['Longitude'])

ohca_df = ohca_df.drop_duplicates(subset=['ReceivedTime', 'Latitude', 'Longitude'])
ohca_df['ReceivedTime'] = pd.to_datetime(ohca_df['ReceivedTime'])
ohca_df['ReceivedTime'] = ohca_df['ReceivedTime'].apply(lambda x: x.date())
ohca_df

,ID_OHCA,ReceivedTime,MinimumResponseTime,Latitude,Longitude,Incident_Location,h3_l7
0,1,2017-01-01,5.666667,36.862471,-76.024169,1000 LINDSLEY DR\r,872af636effffff
1,2,2017-01-01,20.750000,36.766897,-76.042337,2600 SPRINGHAVEN DR\r,872af0c96ffffff
3,4,2017-01-01,11.083333,36.905880,-76.118769,4200 SHORE DR\r,872af6372ffffff
4,5,2017-01-01,0.000000,36.620850,-76.090090,5200 BLACKWATER RD\r,872af0515ffffff
5,6,2017-01-02,0.000000,36.784458,-76.108918,3800 TIFFANY LA\r,872af6266ffffff
...,...,...,...,...,...,...,...
2699,2700,2019-06-28,9.650000,36.789220,-75.978720,600 FLEET DR\r,872af0cb0ffffff
2701,2702,2019-06-29,4.883333,36.842390,-76.145965,200 ARAGONA BL\r,872af635effffff
2702,2703,2019-06-29,4.666667,36.792043,-76.167430,5300 LACROSSE CT\r,872af6274ffffff
2703,2704,2019-06-29,11.400000,36.804559,-76.183715,1200 GENERAL ST\r,872af6276ffffff
2705,2706,2019-06-30,7.133333,36.840078,-76.017284,1600 INDIANA AV\r,872af636affffff

In [8]:
ohca_df.to_csv('ohca_df.csv' , index=False)

In [9]:
cols = np.concatenate((
    poi_df.building.unique(),  # 從 poi_df 中提取唯一的建築類型
))
len(cols)  # 計算列數

h3_l7_df = pd.DataFrame(data={'id': np.unique(np.concatenate((poi_df.h3_l7.unique(), ohca_df.h3_l7.unique())))})

h3_l7_df[cols] = 0

for i in range(poi_df.shape[0]):  # 遍歷 poi_df 中的每一行
    h3_l7_id = poi_df.iloc[i]['h3_l7']  # 獲取當前行的 h3_l7 值
    h3_l7_df.loc[h3_l7_df['id'] == h3_l7_id, poi_df.iloc[i]['building']] += 1  # 根據 building 類型累加計數

C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0
C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0
C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0
C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0
C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0
C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0
C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0
C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0
C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0
C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0
C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0
C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0
C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0
C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0
C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0
C:\Users\Yuan\AppData\Local\Temp\ipykernel_1616\1438246919.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  h3_l7_df[cols] = 0

KeyboardInterrupt:

In [8]:
unique_h3_l7, counts = np.unique(np.array(ohca_df.h3_l7), return_counts = True)
h3_l7_df['ohca'] = 0
for i in range(len(unique_h3_l7)):
    h3_l7_df.loc[h3_l7_df.id == unique_h3_l7[i], 'ohca'] = counts[i]

h3_l7_df
# h3_l7_df.to_csv('h3_l7_df_new.csv' , index=False)

,id,place_of_worship,grave_yard,school,post_office,childcare,university,courthouse,fire_station,library,...,warehouse,sports_centre,detached,boathouse,barn,riding_hall,construction,ship,ruins,ohca
0,872af0424ffffff,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,872af0425ffffff,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,872af0426ffffff,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
3,872af0500ffffff,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,872af0501ffffff,0,0,1,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,872af6373ffffff,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
173,872af6375ffffff,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,20
174,872af6acaffffff,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
175,872af6ad9ffffff,2,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,2
176,872af6adbffffff,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0